version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - echo "Nothing to install here"

  pre_build:
    commands:
      - echo "Preparing to deploy"

  build:
    commands:
      - echo "Deploying to EC2"
      - chmod +x scripts/deploy.sh
      - ./scripts/deploy.sh

artifacts:
  files:
    - '**/*'
